version: '3'

services:
  api:
    build: ./app
    hostname: api
    restart: always
    volumes:
      - .:/code
    env_file:
      - app/.env
    environment:
      FLASK_ENV: development
    ports:
      - 5000:5000

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - database.env
    ports:
      - "27017:27017"
    depends_on:
      - api

  redis:
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

# Helps in data persistance at container deletion.
volumes:
  mongodb_data_container:
  redis-data:
  redis.conf:
  redis_data_cache:
